# Generated by Django 5.1.3 on 2024-11-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fault',
            fields=[
                ('fault_id', models.CharField(max_length=25, primary_key=True, serialize=False, unique=True)),
                ('date_reported', models.IntegerField()),
                ('description', models.TextField(max_length=500, null=True)),
                ('status', models.CharField(max_length=20)),
                ('priority_level', models.CharField(max_length=10)),
                ('resolution_start_time', models.IntegerField(null=True)),
                ('resolution_end_time', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkComponent',
            fields=[
                ('component_id', models.CharField(max_length=25, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(max_length=25)),
                ('manufacturer', models.CharField(max_length=50)),
                ('configuration_details', models.JSONField()),
                ('affects_uptime', models.BooleanField()),
                ('location', models.CharField(max_length=50)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.CharField(max_length=25, primary_key=True, serialize=False, unique=True)),
                ('message', models.TextField(max_length=50)),
                ('status', models.BooleanField()),
                ('created_at', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('technician_id', models.CharField(max_length=25, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=20)),
                ('contact_info', models.JSONField()),
                ('skillset', models.JSONField()),
                ('availability', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=25, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=45)),
                ('role', models.CharField(max_length=20)),
                ('contact_info', models.JSONField()),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
