# Generated by Django 5.1.3 on 2024-11-24 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Counters",
            fields=[
                ("Pid", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=55)),
                ("value", models.IntegerField()),
                ("last_updated", models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="networkcomponent",
            name="configuration_details",
        ),
        migrations.AddField(
            model_name="fault",
            name="affected_component_id",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                to="main.networkcomponent",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fault",
            name="assigned_technician_id",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                to="main.technician",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="networkcomponent",
            name="date_added",
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="notification",
            name="fault_id",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                to="main.fault",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="notification",
            name="user_id",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                to="main.user",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="location",
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="ConfigurationSettings",
            fields=[
                (
                    "configuration_id",
                    models.CharField(
                        max_length=25, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("details", models.JSONField()),
                (
                    "component_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="main.networkcomponent",
                    ),
                ),
            ],
        ),
    ]
