# Generated by Django 5.1.3 on 2024-11-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_counters_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="permissions",
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
    ]
