# Generated by Django 5.1.3 on 2024-11-25 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_user_permissions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="technician",
            name="role",
        ),
    ]
