# Generated by Django 5.1.3 on 2024-11-26 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_remove_technician_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="configurationsettings",
            name="component_id",
        ),
        migrations.AddField(
            model_name="networkcomponent",
            name="configuration_id",
            field=models.ForeignKey(
                blank=True,
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                to="main.configurationsettings",
            ),
            preserve_default=False,
        ),
    ]
