# Generated by Django 5.1.3 on 2024-11-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_remove_configurationsettings_component_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="type",
            field=models.CharField(default=None, max_length=25),
            preserve_default=False,
        ),
    ]
