# Generated by Django 5.1.3 on 2024-11-28 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_notification_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="fault",
            name="reported_user_id",
            field=models.ForeignKey(
                default="USER-001",
                on_delete=django.db.models.deletion.PROTECT,
                to="main.user",
            ),
            preserve_default=False,
        ),
    ]
