# Generated by Django 5.1.3 on 2024-11-29 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_fault_reported_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fault",
            name="reported_user_id",
            field=models.ForeignKey(
                blank=True, on_delete=django.db.models.deletion.PROTECT, to="main.user"
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="user_id",
            field=models.ForeignKey(
                blank=True, on_delete=django.db.models.deletion.PROTECT, to="main.user"
            ),
        ),
    ]
