# Generated by Django 5.1.3 on 2024-11-29 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_alter_fault_reported_user_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fault",
            name="reported_user_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="main.user",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="user_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="main.user",
            ),
        ),
    ]
